### PR TITLE
Added torrents

### PR DESCRIPTION
**Pull request by CoderJolly**
I have added torrents files

### CODE REVIEW

**Comment by anshumanv** [comment]
Hi @CoderJolly, lost this PR among notifications 😞 

Can you rebase? Let's merge this 😄

**Comment by toprak** [comment]
@anshumanv http://www.anime-ultime.net is down, and the rest of them are already in repo except http://animelayer.ru/

**Comment by anshumanv** [comment]
Also, `shanaproject` can also be added

**Comment by toprak** [comment]
It was on my mind, I had forgotten it even though I am an active shanaproject user :D

**Comment by toprak** [comment]
done 9320d9c

**Comment by CoderJolly** [comment]
> Hi @CoderJolly, lost this PR among notifications 😞
> 
> Can you rebase? Let's merge this 😄

Thanks for noticing, I believe it doesn't have relevance now. Will try again this time 😄

**Comment by anshumanv** [comment]
Thanks, feel free to PR with any new additions 😄

**Pull request closed without merging**
