### PR TITLE
Add Russian sites with anime and manga

### PR DESCRIPTION
**Pull request by Sepera-okeq**

### CODE REVIEW

**Review by toprak — COMMENTED** [review]
seems good to me but you can delete catalog from yummyanime.club/catalog it is useless

**Comment by Sepera-okeq** [comment]
I agree, I'll do it now.

**Comment by Sepera-okeq** [comment]
Corrected.

**Comment by toprak** [comment]
Thanks for helping us out!

**Comment by anshumanv** [comment]
Thanks for contributing @Sepera-okeq! 💯

**Pull request merged**
